import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  renderSurfaceDiffAnsi,
  renderSurfacePlain,
  renderSurfaceWithAxes,
  summarizeSurface,
  summarizeSurfaceDiff,
  visualizeAnsi
} from "../src/index.js";
import { buildReviewFrames } from "../examples/review-scene.js";

const outputDir = join(process.cwd(), "docs", "generated");
const { frameA, frameB } = buildReviewFrames();
const plainA = renderSurfacePlain(frameA);
const plainB = renderSurfacePlain(frameB);
const axesA = renderSurfaceWithAxes(frameA);
const axesB = renderSurfaceWithAxes(frameB);
const diffEscaped = visualizeAnsi(renderSurfaceDiffAnsi(frameA, frameB));
const statsA = summarizeSurface(frameA);
const statsB = summarizeSurface(frameB);
const diffStats = summarizeSurfaceDiff(frameA, frameB);

const reviewMarkdown = `# Rendering Review

Generated by \`pnpm review:artifacts\`.

## Frame A

\`\`\`
${plainA}
\`\`\`

## Frame B

\`\`\`
${plainB}
\`\`\`

## Frame B With Axes

\`\`\`
${axesB}
\`\`\`

## Surface Stats

### Frame A

\`\`\`json
${JSON.stringify(statsA, null, 2)}
\`\`\`

### Frame B

\`\`\`json
${JSON.stringify(statsB, null, 2)}
\`\`\`

### Diff A -> B

\`\`\`json
${JSON.stringify(diffStats, null, 2)}
\`\`\`

## Escaped ANSI Diff Preview

\`\`\`
${diffEscaped.slice(0, 4000)}
\`\`\`
`;

await mkdir(outputDir, { recursive: true });
await Promise.all([
  writeFile(join(outputDir, "frame-a.txt"), `${plainA}\n`, "utf8"),
  writeFile(join(outputDir, "frame-b.txt"), `${plainB}\n`, "utf8"),
  writeFile(join(outputDir, "frame-a-axes.txt"), `${axesA}\n`, "utf8"),
  writeFile(join(outputDir, "frame-b-axes.txt"), `${axesB}\n`, "utf8"),
  writeFile(join(outputDir, "frame-diff-escaped.txt"), `${diffEscaped}\n`, "utf8"),
  writeFile(join(outputDir, "review.md"), reviewMarkdown, "utf8")
]);

process.stdout.write(`Wrote review artifacts to ${outputDir}\n`);

